name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: test_estimate_pi.py
      id: test_estimate_pi-py
      uses: classroom-resources/autograding-python-grader@v1
      with:
        timeout: 10
        max-score: 5
        setup-command: pip install pytest numpy
    - name: test_random_unit_vectors.py
      id: test_random_unit_vectors-py
      uses: classroom-resources/autograding-python-grader@v1
      with:
        timeout: 10
        max-score: 5
        setup-command: pip install pytest numpy
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TEST_ESTIMATE_PI-PY_RESULTS: "${{steps.test_estimate_pi-py.outputs.result}}"
        TEST_RANDOM_UNIT_VECTORS-PY_RESULTS: "${{steps.test_random_unit_vectors-py.outputs.result}}"
      with:
        runners: test_estimate_pi-py,test_random_unit_vectors-py
